version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    entrypoint: ["/opt/keycloak/bin/keycloak-entrypoint.sh"]
    user: root               # so we can install jq at startup
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_IMPORT: /opt/keycloak/data/import/x-university.json
    volumes:
      - ./data/import:/opt/keycloak/data/import:ro
      - ./scripts/setup-keycloak.sh:/opt/keycloak/bin/setup-keycloak.sh:ro
      - ./scripts/keycloak-entrypoint.sh:/opt/keycloak/bin/keycloak-entrypoint.sh:ro
    ports:
      - 8080:8080