services:
  db:
    image: postgres:15
    container_name: user-service-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: xuniv_user
      POSTGRES_PASSWORD: xuniv_pass
      POSTGRES_DB: xuniversity
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
volumes:
  pgdata:
