services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5433:5432"   # host 5433 → container 5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: